variables:
  IMAGE: ubuntu:with-hermitcore
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - prepare
  - build
  - test

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - docker build -t ${IMAGE} .
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DTOOLCHAIN_BIN_DIR=/opt/hermit/bin -DCMAKE_INSTALL_PREFIX=/opt/hermit ..
    - make
  image: ${IMAGE}
  tags:
    - docker
  artifacts:
    untracked: true
    expire_in: 1 week
    paths:
      - ./build

# Stage: test
##############################################################################
test:
  stage: test
  script:
    - cd build
    - export TDIR=./local_prefix/opt/hermit/x86_64-hermit/extra
    - export FILES="$TDIR/tests/hello"
    - export PROXY=./local_prefix/opt/hermit/bin/proxy
    - for f in $FILES; do echo "check $f..."; HERMIT_ISLE=qemu HERMIT_CPUS=1 HERMIT_KVM=0 HERMIT_VERBOSE=1 timeout --kill-after=5m 5m $PROXY $f || exit 1; done
  image: ${IMAGE}
  tags:
    - docker
  dependencies:
    - build
